name: AFactionStrike
main: org.asmaster.fstrike.FSMain
depend: [Factions]
version: 1.0
author: ASMaster
description: Plugin to give a faction a strike.
commands: 
      strike:
          usage: /<command>
          description: command to give factions strikes
          
permissions:
      afactionstrike.give:
          default: false